# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCN9Efy1YwGTusaGKaOldyRTEIE-Y-dZ
"""

from transformers import AutoTokenizer,AutoModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
token = tokenizer.tokenize("Trensformers are powerful.")
token_ids = tokenizer. convert_tokens_to_ids(token)

print("Tokens:", token)
print("Token IDS:", token_ids)

import torch
text = " my name is nikita"
model_name = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)
inputs = tokenizer(text, return_tensors="pt")
with torch.no_grad():
  outputs = model(**inputs)
last_hidden_states = outputs.last_hidden_state
print("Embeddings shape:", last_hidden_states.shape)
print(last_hidden_states)



from transformers import pipeline
generator = pipeline("text-generation", model="gpt2")
output = generator("artificlial Intelligence will shape the future of", max_length=50)
print(output[0]['generated_text'])
# print(output)



from transformers import MarianMTModel, MarianTokenizer
model_name = 'Helsinki-NLP/opus-mt-en-de'
tokenizer = MarianTokenizer.from_pretrained(model_name)
moodel = MarianMTModel.from_pretrained(model_name)

text = "Artificial Intelligence is transforming the world."

inputs = tokenizer(text, return_tensors = "pt", padding = True)

translated = model.generate(**inputs)

output = tokenizer.decode(translated[0], skip_special_tokens = True)

print("Translated (Englsish to German):", output)

from transformers import pipeline
sentiment = pipeline("sentiment-analysis")

sentence ="This movie was absolutly wonderful!"

result = sentiment(sentence)
print(result)

from transformers import pipeline
ner = pipeline("ner")

sentence ="tajmahal is a good place to visit"

result = ner(sentence)
print(result)

from transformers import pipeline
qa = pipeline("question-answering",model="distilbert-base-cased-distilled-squad",framework="pt" )# force PyTorch​)​

context = "Artificial Intelligence enables machines to learn and think."

question = "What does Artificial Intelligence enable?"

result = qa(question=question, context=context)

print("Answer:", result["answer"])

